version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerization/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - project_network

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: collection
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network: