"""01_initial-db

Revision ID: 6a0ae71d51cd
Revises: 
Create Date: 2024-03-27 15:44:28.573251

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a0ae71d51cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_url', sa.String(), nullable=False),
    sa.Column('shortened_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('usages', sa.Integer(), nullable=True),
    sa.Column('last_usage', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_url'),
    sa.UniqueConstraint('shortened_url')
    )
    op.create_index(op.f('ix_link_created_at'), 'link', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_created_at'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
