"""08_file

Revision ID: 893e1bfab57d
Revises: e83cd8142e52
Create Date: 2024-04-06 16:20:29.348431

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '893e1bfab57d'
down_revision: Union[str, None] = 'e83cd8142e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('path', sa.String(), nullable=False))
    op.drop_constraint('file_name_key', 'file', type_='unique')
    op.create_unique_constraint(None, 'file', ['path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    op.create_unique_constraint('file_name_key', 'file', ['name'])
    op.drop_column('file', 'path')
    # ### end Alembic commands ###
