"""07_file

Revision ID: e83cd8142e52
Revises: 3fcc60610ba6
Create Date: 2024-04-06 16:11:30.150411

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e83cd8142e52'
down_revision: Union[str, None] = '3fcc60610ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_username_key', 'file', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('file_username_key', 'file', ['username'])
    # ### end Alembic commands ###
